services:
  db:
    container_name: database
    image: postgres:17-alpine
    restart: always
    env_file: 
      - path: ./db/.env
        required: false
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    #Limits for testing
    deploy:
      resources:
        limits:
          memory: 1G  
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file: 
        - path: ./pgadmin/.env
          required: false
    healthcheck:
      #test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      test: ["CMD-SHELL", "timeout 1s bash -c ':> /dev/tcp/localhost/80' || exit 1"]
      #test: ["CMD-SHELL", "curl -f http://localhost:80/misc/ping > /dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    #Limits for testing
    deploy:
      resources:
        limits:
          memory: 1G  
    depends_on:
      db:
        condition: service_healthy        

  backend:
    container_name: backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    env_file: 
        - path: ./backend/.env
          required: false
    environment:
      - TZ=${TZ}

    healthcheck:
    
      #test: ["CMD", "curl", "-f", "http://localhost/api/food"]
      #test: ["CMD-SHELL", "timeout 1s bash -c ':> /dev/tcp/localhost/$$PORT' || exit 1"]
      #test: ["CMD-SHELL", "nc -zv localhost 8080"]
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health/readiness"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    #Limits for testing
    deploy:
      resources:
        limits:
          memory: 1G     
    depends_on:
      db:
        condition: service_healthy   
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    container_name: frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    env_file:
      - path: ./frontend/.env
        required: false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G     
    depends_on:
      backend:
        condition: service_started    

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    environment:
      - TZ=Europe/Belgrade 
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:80"]
      #test: ["CMD-SHELL", "nc -z localhost 80 || exit 1"]
      test: ["CMD-SHELL", "timeout 1s sh -c ':> /dev/tcp/localhost/80' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    #Limits for testing
    deploy:
      resources:
        limits:
          memory: 1G  
    depends_on:
      db:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
       


volumes:
  db_data:      