events{
    worker_connections 1024;
}


http{
    server_tokens off;
    charset  utf-8;
   
    server {
        listen 80;
        server_name localhost;
        location /api/{
            proxy_pass http://backend:8080;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-Host $server_name;
        }
        location /{
            proxy_pass http://pgadmin:80;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-Host $server_name;
            #proxy_set_header X-Script-Name /pgadmin;
        }
        location /db{
            proxy_pass http://db:5432;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
    
}


    