spring:
  application:
    name: ${APP_NAME:Starter}
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/starter}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jackson:
    mapper:
      sort-properties-alphabetically: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
server:
    port: ${PORT:8080}
