spring:
  application:
    name: ${APP_NAME:Starter}
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/starter}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jackson:
    mapper:
      sort-properties-alphabetically: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
server:
    port: ${PORT:8080}
management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      #show-details: always #for debugging, alternative "always/when-authorized"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    root: "warn"
    org.springframework.web: "warn"
    org.hibernate: "error"
  file:
      path: "logs/"
      name: "logs/application.log"
  pattern: 
      file: "%d %-5level - %msg%n"
      console: "%d %-5level - %msg%n"
  logback: 
      rollingpolicy:
        max-file-size: "10MB"
        total-size-cap: "50MB"
        max-history: 5
